name: Build New OTP Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    name: Build OTP for Heroku ${{ matrix.stack }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        stack:
          - 22

    steps:
      - uses: actions/checkout@v4

      - name: Get OTP Version
        id: otp-version
        run: |
          echo "version=${GITHUB_REF/refs\/tags\//}" >> "$GITHUB_OUTPUT"

      - name: Download OTP Source
        env:
          OTP: ${{ steps.otp-version.outputs.version }}
          GH_TOKEN: ${{ github.token }}
        run: |
          wget https://github.com/erlang/otp/archive/OTP-${OTP}.tar.gz
          gh release upload "${OTP}" "OTP-${OTP}.tar.gz" --clobber

      - name: Setup OTP Build
        env:
          OTP: ${{ steps.otp-version.outputs.version }}
        run: |
          mkdir -p build/mount/otp-release-files
          mv OTP-$OTP.tar.gz build/
          cd build
          tar -zxf OTP-$OTP.tar.gz
          mv otp-OTP-$OTP/ mount/

      - name: Build Heroku Stack Image
        env:
          STACK: ${{ matrix.stack }}
        run: docker build -t heroku-$STACK - < stacks/heroku-$STACK.Dockerfile

      - name: Build OTP
        working-directory: build
        env:
          OTP: ${{ steps.otp-version.outputs.version }}
          STACK: ${{ matrix.stack }}
        run: |
          docker run -v $(pwd)/mount:/build -w /build/otp-OTP-$OTP heroku-$STACK ./otp_build autoconf
          docker run -v $(pwd)/mount:/build -w /build/otp-OTP-$OTP heroku-$STACK ./configure --with-ssl --enable-dirty-schedulers
          docker run -v $(pwd)/mount:/build -w /build/otp-OTP-$OTP heroku-$STACK make
          docker run -v $(pwd)/mount:/build -w /build/otp-OTP-$OTP heroku-$STACK make RELEASE_ROOT=/build/otp-release-files release
          docker run -v $(pwd)/mount:/build -w /build/otp-OTP-$OTP heroku-$STACK chmod -R 777 /build/otp-release-files

      - name: Create and Upload Tarball
        working-directory: build
        env:
          OTP: ${{ steps.otp-version.outputs.version }}
          STACK: ${{ matrix.stack }}
          GH_TOKEN: ${{ github.token }}
        run: |
          mv mount/otp-release-files/ OTP-$OTP
          tar -zcf heroku-${STACK}.tar.gz OTP-$OTP
          gh release upload "${OTP}" "heroku-${STACK}.tar.gz" --clobber
